name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -U jupyter-book ghp-import

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Deploy to GitHub Pages
      env:
        GIT_USER: github-actions
        GIT_EMAIL: github-actions@github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${GIT_USER}"
        git config --global user.email "${GIT_EMAIL}"

        ghp-import -n -f -b gh-pages _build/html
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages --force

